### ISSUE TITLE
Kedro Experiment Tracking Product Marketing Strategy

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-devrel#38]
## Context

This captures all the product marketing activities to promote  and encourage awareness and adoption of Kedro Experiment Tracking. 

This includes updating the documentation, preparing a blog post, presentation, and webinar, and distributing the content beyond the existing [Kedro slack](https://join.slack.com/t/kedro-org/shared_invite/zt-1eicp0iw6-nkBvDlfAYb1AUJV7DgBIvw) organisation. 

### Goal
The goal is to  increase adoption of kedro experiment tracking, and Kedro-Viz, especially Kedro-Viz/Kedro users by 30%.

### Target audience
This is targeted to (DS, DE, and low tech)users with a 2 prong approach:

1. Marketing to kedro users to use kedro-viz
2. Marketing to non-kedro users to use kedro/kedro-viz

## Content
This would include:
- What is experiment tracking?
- Why Kedro implemented experiment tracking?
- Why would you choose to use experiment tracking in Kedro vs other tools?
- What features are in experiment tracking for Kedro?
- How did we get to this version of experiment tracking? (user testing process)
- What's the future of this feature?

This content would then be repurposed for different forms and mediums.

## Plan/Checklist
Admin:
- [x] Create Github issues to track product marketing strategy and sub-activities - blog post e.t.c.
- [x] Metrics - Determine success metrics for product marketing, and feature adoption

Key Activities:
- [x] Update Kedro-Viz docs [#2144](https://github.com/kedro-org/kedro-viz/issues/1241) and spaceflight tutorial
- [x] Write and publish blog article - [#1227 ](https://github.com/kedro-org/kedro-viz/issues/1227) - To address all the questions in the content section: Why Kedro implemented experiment tracking?
- [x] Video - Present and record a video walkthrough on kedro experiment tracking (especially for existing users of experiment tracking and user interview/testing participants) -  #45 - To demo the features in Kedro experiment tracking
- [x] Presentation - #46  -  prepare a presentation for internal & external audiences on kedro experiment tracking
- [x] Do a google search on experiment tracking, to benchmark other related content for messaging and positioning 
- [x] Explore other channels beyond Slack, to reach  users 
- [ ] Create a set of content that compares experiment tracking in Kedro to the 3 (or 5) most likely "competitors". This content could be video scripts (to film at a later stage) or just text to publish as potential blog posts or other content marketing.

**Comment by tynandebold** [comment]
Closing this, as we've done the majority of the work and won't action the last remaining to-do item.
