### ISSUE TITLE
Scaling introductory Kedro training

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-devrel#44]
## Description

This follows a conversation in the [Software Engineering for Data Scientists](https://github.com/kedro-org/kedro/issues/2089) about how users learn about Kedro and software engineering principles. This ticket proposes the creation of an Introduction to Kedro YouTube..

## Why is this important? 

We've been running "Kedro Beginner Bootcamp" trainings for many years now and this model is not ideal because: 
- We mostly host internal sessions, so our open-source users don't benefit from these learnings
- We have only run [one external training](https://www.youtube.com/watch?v=NU7LmDZGb6E), which is well-viewed 

So we need to think of ways to scale learning about Kedro beyond the capabilities of the team and this will impact all users. 

## Proposal

We should create an Introduction to Kedro training on YouTube. Some of this work includes: 
- Designing and tweaking the curriculum to fit this platform
- Recording the sessions 
- Defining the learner support model 
- Creating a marketing plan

## Evidence markers

- Users did find Kedro because of DataEngineerOne 
- Users still try and use our old trainings
- There is low-evidence that we should do a Udemy course from @stichbury's research

Therefore, we believe that this will help drive adoption of Kedro.

**Comment by astrojuanlu** [comment]
_Disclaimer 1: Personally, as a user, I was favoring Udemy lately much more than Coursera. So, my research is influenced by my own biases as a learner.
Disclaimer 2: I would love to know more about how people learn _for real_ and not just based on personal anecdata or intuition, but I'm not in that position yet. Some day I will have to read https://teachtogether.tech/ and https://www.learningpirate.com/._

Unsurprisingly, "there is no clear winner". Here are a couple of interesting comparisons I found:

![image](https://user-images.githubusercontent.com/316517/233330703-6976f561-3611-4f1e-a1a1-b69bc0c0d9f4.png)

([source](https://www.linkedin.com/pulse/udemy-vs-coursera-datacamp-which-best-you-faisal-albusairi/))

![image](https://user-images.githubusercontent.com/316517/233330874-dcdf79e1-77b1-4526-b3ef-eaeed56bf32a.png)

([source](https://www.mltut.com/coursera-vs-udemy-for-data-science/))

It's clear that learners value affordable prices. This makes sense with the abundance of free content that is out there. People are willing to pay for good material, but with limits.

Coursera pricing is rather complex for learners:

![image](https://user-images.githubusercontent.com/316517/233331866-89ce265b-3604-417f-ba40-3950f9584636.png)

([source](https://upskillwise.com/coursera-cost/))

On the other hand, Udemy is rather simple: using the platform is free, and courses have a wide range of prices.

In general, the "vibe" I get is that people reach to Coursera when they care more about having certifications from top universities and Big Tech. On the other hand, Udemy has lots of courses created by solopreneurs and independent creators, and I didn't see any emphasis in certifications. The value of certifications themselves is already a nuanced topic.

And finally, just yesterday I was discussing with someone about the feedback loop that tailored learning environments can provide, like the ones Datacamp, Codecademy, or Replit offer. I think these have pros and cons:

- Pros: Provide a quick, tight feedback loop for learners. A super simple interface. A web-based environment they don't have to install, configure, or pay for.
- Cons: Such environment is often totally different from what's used for working (we suffered this with Replit). Also, in my view the tight feedback loop, often reinforced by "fill the gaps" exercises, creates "the illusion of learning" but then people struggle to apply the concepts to complex assignments.

These days I would definitely favor something that has the option of being fully web-based, so learners don't have to install anything, but sticking to either JupyterLab, an alternative notebook interface (although not many of them offer a self-hosted alternative), or VSCode. This means decoupling the learning platform from the IDE. We can still find ways for them to do exercises with a quick feedback loop by adding unit tests, like we did already at https://github.com/kedro-org/kedro-academy/tree/main/swe4ds.

An alternative to such "self-paced with automated exercises" is cohort-based learning - essentially having a "buddy group" or study group to which you can ask questions and hold each other accountable. Coursera offers this option. For Udemy I have observed that some trainers have a separate Discord or Slack. DataTalksClub does a similar thing, with all materials being available for self-paced learning while also offering the option of cohort registration https://github.com/DataTalksClub/data-engineering-zoomcamp

Cohort management, however, does create a bit of overhead, which goes against the objective of scaling.

All things considered, I think we should go for Udemy because

- It has a larger catalog, and more exposure.
- It is perceived as easier to use and more affordable.
- Gives us, as trainers, flexibility to expand into more sophisticated teaching practices.
- Does not tie us to a particular coding environment.

**Comment by astrojuanlu** [comment]
Current focus:

1. Exploring Udemy for instructors
2. Breaking down this task into smaller ones

**Comment by astrojuanlu** [comment]
> Revamped coding exercises – We think this is pretty big for those of you who teach courses in Development and Data Science. Coding exercises are now presented in an IDE-like interface, to more closely match real-world experience. Also, you can add related lectures, hints, and solution explanations.

https://teach.udemy.com/what-weve-done-and-where-were-going-may-2023/

**Comment by stichbury** [comment]
I think the ticket about writing an [Academy blog post](https://github.com/kedro-org/kedro-devrel/issues/25) should become a child of this one since I don't see us writing about Academy until we have something public to unveil on a learning platform.

**Comment by astrojuanlu** [comment]
This is ready for a first review.

**Comment by yetudada** [comment]
I'm done on review! ❤️

**Comment by astrojuanlu** [comment]
I'll be creating issues for the pending materials we have to create today and tomorrow.

**Comment by astrojuanlu** [comment]
First round of recordings done. The studio will get back to me in about 15 days.

**Comment by astrojuanlu** [comment]
Videos uploaded to YouTube.

Pending:

- [ ] Review titles and descriptions
- [ ] Add cards (so that each video is followed by the next in the playlist)
- [ ] Finish blog post (#120)
- [ ] https://github.com/kedro-org/kedro/issues/3302

**Comment by astrojuanlu** [comment]
Just because this has been open for too long and promotion has already started, let's close this one and continue in the two follow-up tickets.

**Comment by rashidakanchwala** [comment]
Udemy has free courses too - - https://www.udemy.com/courses/free/
