### ISSUE TITLE
Collaborative Experiment Tracking Product Launch Strategy

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-devrel#74]
## Context
This captures the product launch activities for the new collaborative experiment tracking feature [#1295](https://github.com/kedro-org/kedro-viz/issues/1295) on Kedro-Viz. This includes preparing a launch blog post, and presentation, and updating/reviewing the documentation. 

### Goal
The goal is to  increase awareness and adoption of kedro experiment tracking, and Kedro-Viz, especially Kedro-Viz/Kedro users.

### Target audience
This is targeted at technical (DS, DE, and MLE) users with a 2 prong approach:

1. Marketing to kedro users to use kedro-viz
2. Marketing to non-kedro users to use kedro/kedro-viz

## Content
This would include:
- What is experiment tracking?
-  What is collaborative experiment tracking?
- Why would you choose to use Kedro experiment tracking vs other tools?

## Plan/Checklist
Admin:
- [x] Create Github issues to track product launch strategy and sub-activities - blog post, and presentation.
Key Activities:
- [x] Blog article - [#73 ](https://github.com/kedro-org/kedro-devrel/issues/73) - Introducing this new feature and it's value proposition for users. This would address the questions in the content section.
- [ ] Presentation - [#72 ](https://github.com/kedro-org/kedro-devrel/issues/72)  - prepare a showcase presentation for internal & external audiences on collaborative experiment tracking.
- [x] Update Kedro-Viz docs [#1353](https://github.com/kedro-org/kedro-viz/issues/1353) with new feature.

**Comment by stichbury** [comment]
Thanks @NeroOkwa -- here's a link to the [template to create a brief about your blog post](https://github.com/kedro-org/kedro/wiki/Kedro-blog-post-brief-template). 

Please could you take it as a guide and plan the post out as a comment here, so we can iterate and get a great structure ready for you and the team to write it up? cc @antonymilne @rashidakanchwala @tynandebold

**Comment by NeroOkwa** [comment]
## Introduction

**What is the blog post about?** 

- This blog post is about collaborative experiment tracking (feature) in Kedro-Viz. Which will allow users to save their experiments to a shared cloud storage, view and compare other (team members)users' experiments.

**What is the problem this blog post solves?** 

- The problem this blog post aims to solve is directing users looking for a way for their team to find (visualise, compare, and collaborate on their pipeline runs) the best performing runs  to this feature in Kedro-Viz.

**Who will find this information useful?** 
- DS, DE, MLE

**What title would you choose?**

- Is your Experiment tracking tool multiplayer?
- How to collaborate with your team on your next pipeline run.
- Experiment tracking: the only way is collaborative.
- Finding your best pipeline run, with your team.

**What keywords are you trying to hit?**

- experiment tracking, mltracking, machine learning, pipeline run, data science pipeline

**How long will this post be? For example, a short 3 minute read, a 20 minute hands-on tutorial, a 10 minute thought-leadership piece.**

- 10 minutes intro and how-to tutorial 

**Will you be including code snippets, screenshots, video, diagrams, or similar?**

- not confirmed.

**How would you promote your post in a tweet or linkedin post?**

- not confirmed.

## Narrative subsections

In this section, please list each of the subsections of the post and what each one covers. Please take this section seriously and give some thought to the flow of your post and how you will take the reader from start to finish.

- Section 1 - The pain points of ingesting, processing, modelling and tracking your data (the data flow)   to get the best parameters, especially when working within a team of DS, DE, and MLE .
- Section 2 - What is Kedro Experiment Tracking (brief)? 
- Section 3 - Collaborative experiment tracking - why it is important and useful.
- Section 4 - Collaborative experiment tracking - the different versions, and what is included in version 1.
- Section 5 - How to get started (tutorial) .

## Conclusion
In this section, we are looking for your pitch. Sell us the value of publishing the blog post and the value to the reader for putting in their time. What have you explained that they can't find elsewhere?

- Any team of users with large amount of data wants to convert that data to business insight. They do that by finding the model with the best outcome (parameters). Reading this post shows the reader the way to achieve this outcome with their team;  collaborative experiment tracking.

**Comment by stichbury** [comment]
Thanks for this, it's a nice summary. Can I suggest a minor revision for the narrative, something like this:

## Introduction 
Covers the pain points of ingesting, processing, modelling and tracking your data (the data flow) to get the best parameters, especially when working within a team of DS, DE, and MLE. Explains that we will show how to optimise your workflow within Kedro-Viz.

> CTA "What is Kedro-Viz?" -- I'll write you a short CTA box to include here

## What is experiment tracking?
Very brief explanation and pointer to old blog
Also introduce collaborative experiment tracking here -- it's still experiment tracking just with collaboration added in. Explain the added value of sharing results (maybe try to get a quote here from a user to say why it's valuable)

## Get started with collaborative experiment tracking on Kedro

### Kedro experiment tracking: version 1
Brief set of features

## How to use Kedro's collaborative experiment tracking
@rashidakanchwala has a good point -- let's get into the tutorial asap
 
## The future of Kedro's collaborative experiment tracking
Explain future plans

> CTA: Find out more about Kedro (this is written already)

**Comment by stichbury** [comment]
Can I request the following as you write the post:

* Please create all screen grabs/videos in the new branding to save updating them
* Please follow the [Kedro style guide](https://github.com/kedro-org/kedro/wiki/Kedro-documentation-style-guide)

**Comment by tynandebold** [comment]
Closing this now, as the last task has it's own ticket here: https://github.com/kedro-org/kedro-devrel/issues/72.
